#!/usr/bin/env python3
"""
Generate e2e/fixtures/synthetic-iep.pdf: the two-page, entirely fictional IEP
the document-pipeline journey uploads.

Why a generator instead of a checked-in binary alone: the PDF has to stay
reviewable. Anyone can read the source of truth below, regenerate, and diff
the text; nobody has to trust an opaque blob that gets fed to OCR + an LLM.
The PDF itself stays checked in so the suite needs no build step.

Design constraints the content satisfies:
  * Zero real child data. Everything is obviously synthetic ("Alex Example",
    "Example Elementary"), and the first line of page 1 says so.
  * Headings match the section names the app knows how to display
    (sectionDisplayNames in IEPSummarizationAndTranslation.tsx: Strengths,
    Eligibility, Present Levels, Goals, Services, Accommodations, Placement,
    Key People, Informed Consent), so the parsing agent has something to map
    onto and the Key Insights accordion renders several items.
  * Enough prose per section that a translation is a real translation: a
    one-line fixture can come back near-identical in two languages, which
    would make "the Spanish tab differs from the English tab" a coin flip.
  * A real text layer (uncompressed Helvetica text operators, WinAnsi), so
    extraction works even if OCR is skipped, and so this script can verify
    the result without any third-party dependency.
  * Two pages, so section page numbers ("Found in pages 1, 2") are non-trivial.

Usage:
    python3 e2e/fixtures/make-synthetic-iep.py          # write + verify
    python3 e2e/fixtures/make-synthetic-iep.py --check  # verify only

Latin-1 only: the built-in Helvetica base font is used with WinAnsiEncoding,
so smart quotes and other non-Latin-1 characters must stay out of the text.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent / "synthetic-iep.pdf"

TITLE_SIZE = 13
HEADING_SIZE = 11
BODY_SIZE = 10
LEADING = 13.5
MARGIN_X = 54
TOP_Y = 752
BOTTOM_Y = 56
PAGE_WIDTH = 612
PAGE_HEIGHT = 792
# Helvetica at 10pt averages ~0.5em per character; 96 characters keeps the
# longest wrapped line inside the right margin with room to spare.
WRAP_COLUMNS = 96

# ---------------------------------------------------------------------------
# The document. ('title'|'heading'|'body'|'gap', text)
# ---------------------------------------------------------------------------
BLOCKS: list[tuple[str, str]] = [
    ("title", "SYNTHETIC TEST DOCUMENT - NOT A REAL IEP"),
    ("body", "Generated by e2e/fixtures/make-synthetic-iep.py for automated pipeline tests. "
             "Every name, date, score and service below is invented."),
    ("gap", ""),
    ("title", "Individualized Education Program (IEP)"),
    ("body", "Student: Alex Example. Date of birth: March 3, 2016. Grade: 4. "
             "School: Example Elementary School, Exampleville Unified School District. "
             "IEP meeting date: October 14, 2025. Annual review due: October 13, 2026. "
             "Three-year reevaluation due: October 13, 2027."),
    ("gap", ""),

    ("heading", "Eligibility"),
    ("body", "The IEP team determined that Alex meets the eligibility criteria for special education "
             "and related services under the category of Specific Learning Disability, with a secondary "
             "area of concern in speech and language. The determination is based on a review of "
             "classroom work samples, curriculum-based measures collected over twelve weeks, a "
             "psychoeducational assessment completed in September 2025, and parent and teacher input. "
             "The team agreed that the learning difficulties are not primarily the result of limited "
             "English proficiency, lack of instruction in reading or mathematics, or environmental "
             "factors."),
    ("gap", ""),

    ("heading", "Strengths"),
    ("body", "Alex is curious, persistent, and highly motivated by hands-on science and building "
             "projects. Teachers describe Alex as a kind classmate who volunteers to help peers set up "
             "experiments and clean up materials. Alex has strong oral comprehension: when a passage is "
             "read aloud, Alex answers inferential questions accurately and retells the main events in "
             "order. Alex enjoys drawing detailed diagrams to explain ideas and uses that strength to "
             "show understanding when writing is difficult. At home, Alex builds elaborate models and "
             "explains how each part works."),
    ("gap", ""),

    ("heading", "Present Levels of Academic Achievement and Functional Performance"),
    ("body", "Reading: Alex reads grade-level connected text at 62 words correct per minute with 91 "
             "percent accuracy; the fourth-grade winter benchmark is 105 words correct per minute. "
             "Decoding multisyllabic words and applying vowel teams remain the largest barriers. "
             "Comprehension of independently read text falls to roughly 55 percent of questions "
             "answered correctly, compared with 90 percent when the same passage is read aloud."),
    ("body", "Writing: Alex composes four to five sentence paragraphs with a clear topic sentence when "
             "given a graphic organizer, and one to two sentences without one. Spelling of "
             "high-frequency words is inconsistent, which slows drafting."),
    ("body", "Mathematics: Alex computes multi-digit addition and subtraction with regrouping at "
             "grade level and is fluent with multiplication facts through the fives. Multi-step word "
             "problems are difficult when the reading load is high; accuracy rises from 40 percent to "
             "85 percent when problems are read aloud."),
    ("body", "Communication and behavior: Alex participates willingly in small groups and needs extra "
             "wait time to organize longer spoken answers. Attendance is regular and no behavior "
             "concerns affect access to instruction."),
    ("gap", ""),

    ("heading", "Annual Goals"),
    ("body", "Goal 1 (Reading fluency): By October 2026, given a fourth-grade passage, Alex will read "
             "aloud at 95 words correct per minute with at least 96 percent accuracy in three "
             "consecutive weekly probes, as measured by curriculum-based measurement."),
    ("body", "Goal 2 (Reading comprehension): By October 2026, after independently reading a "
             "fourth-grade informational passage, Alex will answer literal and inferential questions "
             "with 80 percent accuracy across four consecutive assessments."),
    ("body", "Goal 3 (Written expression): By October 2026, Alex will write an organized paragraph with "
             "a topic sentence, three supporting details and a closing sentence, scoring 3 or higher on "
             "the district four-point writing rubric in three of four samples."),
    ("body", "Goal 4 (Self-advocacy): By October 2026, in four of five observed opportunities, Alex "
             "will independently request an accommodation, such as a read-aloud or extra time, when a "
             "task requires heavy reading."),
    ("gap", ""),

    ("heading", "Services"),
    ("body", "Specialized academic instruction in reading and written expression: 240 minutes per week, "
             "delivered in a small group of no more than five students by the resource specialist, "
             "beginning October 21, 2025 and continuing through October 13, 2026."),
    ("body", "Speech and language therapy: 30 minutes per week in a small group, plus 30 minutes per "
             "month of consultation between the speech-language pathologist and the general education "
             "teacher."),
    ("body", "Extended school year services: the team determined that extended school year services "
             "are not required at this time and will revisit the question at the spring progress "
             "review."),
    ("gap", ""),

    ("heading", "Accommodations and Supports"),
    ("body", "Extended time of up to time and a half on assessments and written assignments; "
             "text-to-speech or an adult read-aloud for directions and for any text-heavy assessment "
             "that is not measuring decoding; preferential seating near the point of instruction; "
             "chunked assignments with checkpoints; access to a word bank and a personal spelling "
             "list; graphic organizers for all extended writing; and a printed copy of class notes. "
             "Program supports for staff include monthly consultation with the resource specialist and "
             "training in the district's structured literacy routines."),
    ("gap", ""),

    ("heading", "Placement and Least Restrictive Environment"),
    ("body", "Alex is placed in the general education fourth-grade classroom for approximately 86 "
             "percent of the instructional week, leaving the classroom only for specialized academic "
             "instruction and speech services. The team considered full-time general education with "
             "consultation only and rejected it because the intensity of reading instruction Alex needs "
             "cannot be delivered in that setting. Alex participates with nondisabled peers in "
             "lunch, recess, assemblies, science, art and all school-wide activities."),
    ("gap", ""),

    ("heading", "Progress Reporting and Key People"),
    ("body", "Progress toward annual goals is reported to the family four times per year, on the same "
             "schedule as report cards. IEP team members: Jordan Example, parent; Riley Sample, general "
             "education teacher; Casey Fictional, education specialist; Dr. Pat Placeholder, school "
             "psychologist; Sam Notreal, speech-language pathologist; and Avery Invented, "
             "administrator designee. The family's preferred language for written communication is "
             "recorded in the district system, and an interpreter was offered for the meeting."),
    ("gap", ""),

    ("heading", "Informed Consent"),
    ("body", "The parent was given a copy of the procedural safeguards, the notice was explained in the "
             "meeting, and the parent consented to the initial provision of the special education and "
             "related services described in this document. The parent may revoke consent in writing at "
             "any time. Parent signature: Jordan Example (fictional). Date: October 14, 2025."),
    ("gap", ""),
    ("body", "End of synthetic test document. This file exists only so automated tests can exercise "
             "the upload, OCR, analysis and translation pipeline end to end."),
]


def wrap(text: str, columns: int = WRAP_COLUMNS) -> list[str]:
    """Greedy word wrap; the built-in fonts have no metrics table here."""
    lines: list[str] = []
    current = ""
    for word in text.split():
        candidate = f"{current} {word}".strip()
        if len(candidate) <= columns:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def layout() -> list[list[tuple[str, str]]]:
    """Split the blocks into pages of (kind, line) entries."""
    pages: list[list[tuple[str, str]]] = []
    page: list[tuple[str, str]] = []
    y = TOP_Y

    def advance(amount: float) -> None:
        nonlocal y, page
        y -= amount
        if y < BOTTOM_Y:
            pages.append(page)
            page = []
            y = TOP_Y

    for kind, text in BLOCKS:
        if kind == "gap":
            advance(LEADING * 0.6)
            continue
        columns = WRAP_COLUMNS if kind == "body" else int(WRAP_COLUMNS * 0.85)
        for line in wrap(text, columns):
            page.append((kind, line))
            advance(LEADING if kind == "body" else LEADING * 1.25)
    if page:
        pages.append(page)
    return pages


def content_stream(lines: list[tuple[str, str]]) -> bytes:
    out = ["BT", f"1 0 0 1 {MARGIN_X} {TOP_Y} Tm", f"{LEADING} TL"]
    current_font = None
    for kind, line in lines:
        font = {
            "title": ("/F2", TITLE_SIZE),
            "heading": ("/F2", HEADING_SIZE),
            "body": ("/F1", BODY_SIZE),
        }[kind]
        if font != current_font:
            out.append(f"{font[0]} {font[1]} Tf")
            current_font = font
        out.append(f"({escape(line)}) Tj")
        out.append("T*")
    out.append("ET")
    return "\n".join(out).encode("latin-1")


def build_pdf(pages: list[list[tuple[str, str]]]) -> bytes:
    objects: list[bytes] = []

    def add(body: bytes) -> int:
        objects.append(body)
        return len(objects)  # 1-based object number

    font_regular = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
                       b"/Encoding /WinAnsiEncoding >>")
    font_bold = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold "
                    b"/Encoding /WinAnsiEncoding >>")

    # Reserve the Pages object number so page objects can point at their parent.
    pages_obj = add(b"")  # filled in below

    page_ids: list[int] = []
    for page_lines in pages:
        stream = content_stream(page_lines)
        contents = add(b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream")
        page_ids.append(add(
            b"<< /Type /Page /Parent %d 0 R /MediaBox [0 0 %d %d] "
            b"/Resources << /Font << /F1 %d 0 R /F2 %d 0 R >> >> /Contents %d 0 R >>"
            % (pages_obj, PAGE_WIDTH, PAGE_HEIGHT, font_regular, font_bold, contents)
        ))

    kids = b" ".join(b"%d 0 R" % pid for pid in page_ids)
    objects[pages_obj - 1] = (b"<< /Type /Pages /Kids [%s] /Count %d >>" % (kids, len(page_ids)))
    catalog = add(b"<< /Type /Catalog /Pages %d 0 R >>" % pages_obj)

    out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0]
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % number + body + b"\nendobj\n"

    xref_at = len(out)
    out += b"xref\n0 %d\n" % (len(objects) + 1)
    out += b"0000000000 65535 f \n"
    for offset in offsets[1:]:
        out += b"%010d 00000 n \n" % offset
    out += (b"trailer\n<< /Size %d /Root %d 0 R >>\nstartxref\n%d\n%%%%EOF\n"
            % (len(objects) + 1, catalog, xref_at))
    return bytes(out)


# ---------------------------------------------------------------------------
# Verification: the text layer must be extractable, without needing pdftotext.
# ---------------------------------------------------------------------------
TJ = re.compile(rb"\((?:\\.|[^\\()])*\)\s*Tj")


def extracted_text(pdf: bytes) -> str:
    pieces = []
    for match in TJ.finditer(pdf):
        raw = match.group()[1:match.group().rfind(b")")]
        pieces.append(raw.decode("latin-1")
                      .replace(r"\(", "(").replace(r"\)", ")").replace(r"\\", "\\"))
    return " ".join(pieces)


def verify(pdf: bytes) -> None:
    problems = []
    if not pdf.startswith(b"%PDF-"):
        problems.append("missing %PDF- header")
    page_count = pdf.count(b"/Type /Page ")
    if page_count < 1:
        problems.append("no page objects")

    text = " ".join(extracted_text(pdf).split())
    for _, source in BLOCKS:
        # Wrapping breaks lines, so check a distinctive fragment of each block.
        probe = " ".join(source.split()[:6])
        if probe and probe not in text:
            problems.append(f"text layer is missing: {probe!r}")
    for expected in ("Alex Example", "Eligibility", "Annual Goals", "Services",
                     "Accommodations", "Informed Consent"):
        if expected not in text:
            problems.append(f"expected heading/name absent from the text layer: {expected}")

    if problems:
        print("FAILED verification:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        raise SystemExit(1)

    print(f"{OUTPUT.name}: {len(pdf)} bytes, {page_count} pages, "
          f"{len(text.split())} extractable words - OK")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the existing PDF instead of rewriting it")
    args = parser.parse_args()

    if args.check:
        verify(OUTPUT.read_bytes())
        return

    pdf = build_pdf(layout())
    OUTPUT.write_bytes(pdf)
    verify(pdf)


if __name__ == "__main__":
    main()
