/**
 * The synthetic encrypted PDFs encrypted-pdf.spec.ts uploads: built in the
 * test process, handed to Playwright as bytes, never written to disk.
 *
 * Nothing from docs/sample-ieps/ may be used here, and that prohibition is
 * not decorative. Those reference IEPs are partly-redacted real student
 * records, and a failing Playwright test uploads screenshots, video and a
 * trace as CI artifacts, so putting one through this journey would put a real
 * child's record in a build artifact. Everything below is drawn from scratch
 * by jsPDF, the same way the frontend's own
 * lib/user-interface/app/src/common/pdf-decrypt.lossless.test.ts builds its
 * fixture.
 *
 * Two files, because telling two shapes of "encrypted" apart is the entire
 * job of the flow under test (pdf-decrypt.ts's docblock has the long
 * version):
 *
 *  - OWNER-RESTRICTED: an encryption dictionary whose USER password is empty.
 *    A district PDF that blocks printing or copying; the parent was never
 *    asked for anything and their own reader never prompted them. It has to
 *    upload silently.
 *  - PASSWORD-PROTECTED: a real, non-empty user password. It has to prompt.
 *
 * jsPDF writes both as RC4 40-bit (/V 1 /R 2), the one scheme its `encryption`
 * option supports, and `{ ownerPassword }` on its own leaves the user password
 * empty, which is exactly the first case. That is checked rather than assumed:
 * see usesEmptyUserPassword below, which recomputes /U from the bytes, and the
 * fixture postconditions at the top of each stage in the spec.
 */
import { createHash } from 'crypto';
import { jsPDF } from 'jspdf';

/** Shaped for Playwright's setInputFiles({ name, mimeType, buffer }), which
 * takes a file the test holds in memory rather than a path on disk. */
export interface SyntheticPdfFile {
  name: string;
  mimeType: string;
  buffer: Buffer;
}

/**
 * The shape the app's own detector looks for: /Encrypt followed by an
 * indirect reference or an inline dictionary (ENCRYPT_ENTRY_PATTERN in
 * lib/user-interface/app/src/common/pdf-encryption.ts, where the reasoning
 * lives).
 *
 * Deliberately a copy rather than an import of that constant. This suite is a
 * black-box test of a DEPLOYED build, which can be older than the source tree
 * it is run from; importing the frontend's current constant would claim a
 * precision the setup does not have, and would drag a frontend module into a
 * package CI installs on its own.
 */
const ENCRYPT_ENTRY_PATTERN = /\/Encrypt\s+(?:\d+\s+\d+\s+R\b|<<)/;

/** US Letter, in PDF points (1/72in), matching a real IEP page. */
const PAGE_SIZE_PT: [number, number] = [612, 792];

/**
 * The 32-byte padding string every revision of the PDF standard security
 * handler pads a password with (the constant given in the spec's Algorithm
 * 2). A password shorter than 32 bytes is filled out with its leading bytes;
 * an EMPTY password is therefore just this string.
 */
const PASSWORD_PAD = Buffer.from([
  0x28, 0xbf, 0x4e, 0x5e, 0x4e, 0x75, 0x8a, 0x41, 0x64, 0x00, 0x4e, 0x56, 0xff, 0xfa, 0x01, 0x08,
  0x2e, 0x2e, 0x00, 0xb6, 0xd0, 0x68, 0x3e, 0x80, 0x2f, 0x0c, 0xa9, 0xfe, 0x64, 0x53, 0x69, 0x7a,
]);

/** /V 1 is the 40-bit RC4 scheme, i.e. a 5-byte file key. */
const RC4_40_BIT_KEY_LENGTH = 5;

function syntheticPdf(
  name: string,
  encryption: { userPassword?: string; ownerPassword?: string }
): SyntheticPdfFile {
  const doc = new jsPDF({ unit: 'pt', format: PAGE_SIZE_PT, encryption });
  doc.setFontSize(14);
  doc.text('SYNTHETIC E2E FIXTURE', 40, 80);
  doc.setFontSize(11);
  doc.text('Generated by e2e/helpers/encrypted-pdf.ts. This is not an IEP.', 40, 110);
  doc.text('No student, family, school or district appears in this file.', 40, 130);
  return { name, mimeType: 'application/pdf', buffer: Buffer.from(doc.output('arraybuffer')) };
}

/**
 * Obviously synthetic on sight, and never typed into the app: it is the OWNER
 * password, which only restricts permissions. The parent never sees it and
 * the browser never asks for it.
 */
const OWNER_RESTRICTION_PASSWORD = 'e2e-owner-restriction-never-typed';

/** A district PDF that blocks printing: encrypted, but with an empty user
 * password, so it opens with no prompt anywhere. */
export function ownerRestrictedPdf(): SyntheticPdfFile {
  return syntheticPdf('e2e-owner-restricted.pdf', { ownerPassword: OWNER_RESTRICTION_PASSWORD });
}

/** A PDF a parent genuinely has to type a password to open. */
export function passwordProtectedPdf(userPassword: string): SyntheticPdfFile {
  return syntheticPdf('e2e-password-protected.pdf', {
    userPassword,
    ownerPassword: OWNER_RESTRICTION_PASSWORD,
  });
}

/** True if these bytes carry the /Encrypt entry the app keys off. Scans the
 * whole file, not just the tail the app reads, because a fixture is small and
 * the strict answer is the useful one here. */
export function hasEncryptEntry(bytes: Buffer): boolean {
  return ENCRYPT_ENTRY_PATTERN.test(bytes.toString('latin1'));
}

/** RC4, in the ~15 lines it takes, because node's crypto no longer offers it
 * under OpenSSL 3 without the legacy provider. Used only to re-derive a
 * fixture's /U entry below; nothing secret passes through it. */
function rc4(key: Buffer, data: Buffer): Buffer {
  const s = Array.from({ length: 256 }, (_, i) => i);
  let j = 0;
  for (let i = 0; i < 256; i++) {
    j = (j + s[i] + key[i % key.length]) & 0xff;
    [s[i], s[j]] = [s[j], s[i]];
  }
  const out = Buffer.alloc(data.length);
  let i = 0;
  j = 0;
  for (let n = 0; n < data.length; n++) {
    i = (i + 1) & 0xff;
    j = (j + s[i]) & 0xff;
    [s[i], s[j]] = [s[j], s[i]];
    out[n] = data[n] ^ s[(s[i] + s[j]) & 0xff];
  }
  return out;
}

interface StandardSecurityHandler {
  revision: number;
  version: number;
  /** The owner-password entry, 32 bytes. */
  o: Buffer;
  /** The user-password entry, 32 bytes: what this module recomputes. */
  u: Buffer;
  /** The permissions flags, a signed 32-bit integer. */
  permissions: number;
  /** The first element of the trailer's /ID, which the file key is built over. */
  firstFileId: Buffer;
}

function readStandardSecurityHandler(bytes: Buffer): StandardSecurityHandler {
  const text = bytes.toString('latin1');
  // Scoped to the encryption dictionary itself (jsPDF writes it flat, with no
  // nested dictionary before the closing >>), so /P cannot pick up a key of
  // the same name from a page or the document catalog.
  const dictionary = /\/Filter\s*\/Standard[\s\S]*?>>/.exec(text)?.[0];
  if (!dictionary) {
    throw new Error(
      'no /Filter /Standard encryption dictionary in the generated fixture: jsPDF stopped ' +
      'encrypting, or writes the dictionary differently now'
    );
  }

  const read = (pattern: RegExp, what: string): string => {
    const match = pattern.exec(dictionary);
    if (!match) throw new Error(`the generated fixture's encryption dictionary has no ${what}`);
    return match[1];
  };
  const fileId = /\/ID\s*\[\s*<([0-9a-fA-F]+)>/.exec(text);
  if (!fileId) throw new Error('the generated fixture has no /ID in its trailer');

  return {
    revision: Number(read(/\/R\s+(\d+)/, '/R')),
    version: Number(read(/\/V\s+(\d+)/, '/V')),
    o: Buffer.from(read(/\/O\s*<([0-9a-fA-F]+)>/, '/O'), 'hex'),
    u: Buffer.from(read(/\/U\s*<([0-9a-fA-F]+)>/, '/U'), 'hex'),
    permissions: Number(read(/\/P\s+(-?\d+)/, '/P')),
    firstFileId: Buffer.from(fileId[1], 'hex'),
  };
}

/**
 * True when the file's /U entry is exactly what the standard security handler
 * computes for an EMPTY user password, i.e. the document is owner-restricted
 * only and opens with no password at all.
 *
 * Recomputed from the bytes rather than taken on trust, because without it
 * both halves of the journey can pass for the wrong reason: "no prompt
 * appeared" is equally what an unencrypted file produces, and "a prompt
 * appeared" is equally what a file carrying a user password nobody meant to
 * set would produce. This is the thing that says which of the two shapes
 * jsPDF actually wrote.
 *
 * Implements only the revision jsPDF emits (/V 1 /R 2, RC4 40-bit) and throws
 * on anything else, so a jsPDF change surfaces as a legible failure instead of
 * a quiet `false`. Algorithm 2 builds the file key from the padded user
 * password, /O, /P and the first /ID element; Algorithm 4 (revision 2) then
 * defines /U as RC4(file key, the padding string).
 */
export function usesEmptyUserPassword(bytes: Buffer): boolean {
  const handler = readStandardSecurityHandler(bytes);
  if (handler.version !== 1 || handler.revision !== 2) {
    throw new Error(
      `the generated fixture uses /V ${handler.version} /R ${handler.revision}, not the RC4 ` +
      '40-bit (/V 1 /R 2) scheme this check implements: teach it the new revision rather ' +
      'than dropping the check'
    );
  }

  const permissions = Buffer.alloc(4);
  permissions.writeInt32LE(handler.permissions);
  const fileKey = createHash('md5')
    .update(PASSWORD_PAD) // an empty user password IS the padding string
    .update(handler.o)
    .update(permissions)
    .update(handler.firstFileId)
    .digest()
    .subarray(0, RC4_40_BIT_KEY_LENGTH);

  return rc4(fileKey, PASSWORD_PAD).equals(handler.u);
}
